const state = { entries: [], query: new URLSearchParams(location.search).get('q') || '', kind: new URLSearchParams(location.search).get('kind') || 'all', sort: new URLSearchParams(location.search).get('sort') || 'quality' };
const kinds = ['all', 'skill', 'plugin', 'mcp', 'agents', 'action', 'tool'];
const labels = { all: 'All', skill: 'Skills', plugin: 'Plugins', mcp: 'MCP servers', agents: 'AGENTS.md', action: 'Actions', tool: 'Tools' };
const safeUrl = (value) => { try { const url = new URL(value); return ['http:', 'https:'].includes(url.protocol) ? url.href : '#'; } catch { return '#'; } };
const formatNumber = (value) => value == null ? 'n/a' : new Intl.NumberFormat('en', { notation: value > 9999 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value);
const el = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text != null) node.textContent = text; return node; };

function syncUrl() { const params = new URLSearchParams(); if (state.query) params.set('q', state.query); if (state.kind !== 'all') params.set('kind', state.kind); if (state.sort !== 'quality') params.set('sort', state.sort); history.replaceState(null, '', `${location.pathname}${params.size ? `?${params}` : ''}`); }
function renderFilters() { const root = document.querySelector('#filters'); root.replaceChildren(...kinds.map((kind) => { const count = kind === 'all' ? state.entries.length : state.entries.filter((entry) => entry.kind === kind).length; const button = el('button', `filter${state.kind === kind ? ' active' : ''}`); button.type = 'button'; button.append(el('span','filter-label',labels[kind]), el('span','filter-count',String(count))); button.onclick = () => { state.kind = kind; render(); }; return button; })); }
function matches(entry) { const haystack = [entry.title, entry.summary, entry.repository.owner, entry.repository.name, ...(entry.topics || [])].join(' ').toLowerCase(); return (state.kind === 'all' || entry.kind === state.kind) && haystack.includes(state.query.trim().toLowerCase()); }
function sorted(entries) { return [...entries].sort((a,b) => state.sort === 'stars' ? (b.metadata.stars ?? -1) - (a.metadata.stars ?? -1) : state.sort === 'updated' ? String(b.metadata.updatedAt ?? '').localeCompare(String(a.metadata.updatedAt ?? '')) : state.sort === 'name' ? a.title.localeCompare(b.title) : b.score.total - a.score.total || a.title.localeCompare(b.title)); }
function evidenceLink(entry, pathValue) { const base = safeUrl(entry.repository.url); if (base === '#') return '#'; const branch = encodeURIComponent(entry.metadata.defaultBranch || 'main'); const type = pathValue.includes('.') ? 'blob' : 'tree'; const encodedPath = pathValue.split('/').map((part) => encodeURIComponent(part)).join('/'); return `${base}/${type}/${branch}/${encodedPath}`; }
function evidenceNode(entry, checkId, value) {
  if (checkId === 'transparency.provenance' || /^https?:\/\//.test(value)) { const link = el('a','evidence-link',value); link.href = safeUrl(value); link.target = '_blank'; link.rel = 'noreferrer'; return link; }
  if (checkId === 'spec.artifact' || checkId === 'docs.basics') { const link = el('a','evidence-link',value); link.href = evidenceLink(entry, value); link.target = '_blank'; link.rel = 'noreferrer'; return link; }
  return el('span','evidence-text',value);
}
function card(entry) { const article = el('article','card'); const top = el('div','card-top'); top.append(el('span','kind',labels[entry.kind])); top.append(el('div',`score${entry.score.ranked ? '' : ' unranked'}`,entry.score.ranked ? String(entry.score.total) : 'Unranked')); const title = el('h3','',entry.title); const owner = el('p','owner',`${entry.repository.owner}/${entry.repository.name}`); const summary = el('p','summary',entry.summary); const topics = el('div','topics'); for (const topic of entry.topics || []) topics.append(el('span','topic',topic)); const signals = el('div','signals'); signals.append(el('span','',`★ ${formatNumber(entry.metadata.stars)}`),el('span','',`Forks ${formatNumber(entry.metadata.forks)}`),el('span','',entry.license)); const details = document.createElement('details'); details.className = 'evidence'; const detailsSummary = document.createElement('summary'); detailsSummary.textContent = 'Evidence and score'; const evidenceBody = el('div','evidence-body'); for (const check of entry.score.checks) { const row = el('div','check-row'); row.append(el('span','',check.label),el('strong','',`+${check.points}`)); const evidence = el('small',''); if (check.evidence.length) check.evidence.forEach((value, index) => { if (index) evidence.append(' · '); evidence.append(evidenceNode(entry, check.id, value)); }); else evidence.textContent = 'No evidence'; row.append(evidence); evidenceBody.append(row); } if (entry.metadata.status && entry.metadata.status !== 'fresh') evidenceBody.append(el('p','warning',entry.metadata.warnings?.join(' ') || `Metadata status: ${entry.metadata.status}`)); details.append(detailsSummary,evidenceBody); const link = el('a','card-link','View repository'); link.href = safeUrl(entry.repository.url); link.target = '_blank'; link.rel = 'noreferrer'; article.append(top,title,owner,summary,topics,signals,details,link); return article; }
function render() { renderFilters(); syncUrl(); const entries = sorted(state.entries.filter(matches)); document.querySelector('#results').replaceChildren(...entries.map(card)); document.querySelector('#result-count').textContent = `${entries.length} result${entries.length === 1 ? '' : 's'}`; document.querySelector('#empty').hidden = entries.length !== 0; }

async function start() { const response = await fetch('./api/v1/catalog.json'); if (!response.ok) throw new Error('Catalog unavailable'); const catalog = await response.json(); state.entries = catalog.entries; document.querySelector('#entry-count').textContent = String(catalog.entries.length); document.querySelector('#ranked-count').textContent = String(catalog.entries.filter((entry) => entry.score.ranked).length); document.querySelector('#updated-at').textContent = new Date(catalog.generatedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'}); const banner = document.querySelector('#status-banner'); if (catalog.refreshStatus !== 'fresh') { banner.hidden = false; banner.textContent = catalog.refreshStatus === 'partial' ? 'Some GitHub metadata could not be refreshed. Affected entries are marked in their evidence panels.' : 'This catalog is a cached or offline build. Quality signals may be stale.'; } const search = document.querySelector('#search'); search.value = state.query; search.oninput = () => { state.query = search.value; render(); }; const sort = document.querySelector('#sort'); sort.value = state.sort; sort.onchange = () => { state.sort = sort.value; render(); }; render(); }
start().catch(() => { document.querySelector('#empty').hidden = false; document.querySelector('#empty h3').textContent = 'Catalog unavailable'; document.querySelector('#empty p').textContent = 'The generated API could not be loaded.'; });
